#ifndef _STUB_CAMERA_METADATA_HIDDEN_H
#define _STUB_CAMERA_METADATA_HIDDEN_H

#include <system/camera_metadata.h>

#ifdef __cplusplus
extern "C" {
#endif

// Available capabilities enum
typedef enum {
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE = 0,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_SENSOR = 1,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_POST_PROCESSING = 2,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_RAW = 3,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_PRIVATE_REPROCESSING = 4,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS = 5,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE = 6,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING = 7,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT = 8,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO = 9,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MOTION_TRACKING = 10,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_LOGICAL_MULTI_CAMERA = 11,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME = 12,
    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_SECURE_IMAGE_DATA = 13,
} camera_metadata_enum_android_request_available_capabilities_t;

typedef camera_metadata_enum_android_request_available_capabilities_t camera_metadata_enum_android_request_available_capabilities;

#ifdef __cplusplus
}
#endif

#endif // _STUB_CAMERA_METADATA_HIDDEN_H
